apiVersion: skaffold/v2beta22
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/auth-mongo-depl.yaml
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: secure-racer-348221
  artifacts:
    - image: melzohery/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: './src/**/*.ts'