apiVersion: v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth
  template:
    replicas: 1
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: melzohery/auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 5000
    targetPort: 5000
    name: 'auth'
    protocol: TCP
