apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
      - name: tickets
        image: melzohery/tickets
        env:
        - name: JWT_SECRET
          value: "m.zohery1998@gmail.com"
        - name: JWT_EXPIRE
          value: "2d"
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
  - port: 5000
    targetPort: 5000
    name: tickets
    protocol: TCP
